# Generated by Django 6.0.3 on 2026-03-07 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('manufacturer', models.CharField(max_length=120)),
                ('plastic', models.CharField(max_length=80)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=60)),
                ('acquired_at', models.DateTimeField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discs', to='collection.collection')),
            ],
            options={
                'ordering': ['-acquired_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BagDisc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_discs', to='collection.collection')),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_entries', to='collection.disc')),
            ],
            options={
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('collection', 'disc'), name='unique_disc_in_collection_bag')],
            },
        ),
    ]
